
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.933+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "asyncFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class AsyncFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.AsyncFault asyncFault;

    public AsyncFault() {
        super();
    }
    
    public AsyncFault(String message) {
        super(message);
    }
    
    public AsyncFault(String message, Throwable cause) {
        super(message, cause);
    }

    public AsyncFault(String message, com.netsuite.webservices.v2016_2.platform.faults.AsyncFault asyncFault) {
        super(message);
        this.asyncFault = asyncFault;
    }

    public AsyncFault(String message, com.netsuite.webservices.v2016_2.platform.faults.AsyncFault asyncFault, Throwable cause) {
        super(message, cause);
        this.asyncFault = asyncFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.AsyncFault getFaultInfo() {
        return this.asyncFault;
    }
}
