
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.886+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "exceededRequestLimitFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class ExceededRequestLimitFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestLimitFault exceededRequestLimitFault;

    public ExceededRequestLimitFault() {
        super();
    }
    
    public ExceededRequestLimitFault(String message) {
        super(message);
    }
    
    public ExceededRequestLimitFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRequestLimitFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestLimitFault exceededRequestLimitFault) {
        super(message);
        this.exceededRequestLimitFault = exceededRequestLimitFault;
    }

    public ExceededRequestLimitFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestLimitFault exceededRequestLimitFault, Throwable cause) {
        super(message, cause);
        this.exceededRequestLimitFault = exceededRequestLimitFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestLimitFault getFaultInfo() {
        return this.exceededRequestLimitFault;
    }
}
