
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.893+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "exceededRequestSizeFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class ExceededRequestSizeFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestSizeFault exceededRequestSizeFault;

    public ExceededRequestSizeFault() {
        super();
    }
    
    public ExceededRequestSizeFault(String message) {
        super(message);
    }
    
    public ExceededRequestSizeFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRequestSizeFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestSizeFault exceededRequestSizeFault) {
        super(message);
        this.exceededRequestSizeFault = exceededRequestSizeFault;
    }

    public ExceededRequestSizeFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestSizeFault exceededRequestSizeFault, Throwable cause) {
        super(message, cause);
        this.exceededRequestSizeFault = exceededRequestSizeFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.ExceededRequestSizeFault getFaultInfo() {
        return this.exceededRequestSizeFault;
    }
}
