
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.873+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "exceededUsageLimitFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class ExceededUsageLimitFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.ExceededUsageLimitFault exceededUsageLimitFault;

    public ExceededUsageLimitFault() {
        super();
    }
    
    public ExceededUsageLimitFault(String message) {
        super(message);
    }
    
    public ExceededUsageLimitFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededUsageLimitFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededUsageLimitFault exceededUsageLimitFault) {
        super(message);
        this.exceededUsageLimitFault = exceededUsageLimitFault;
    }

    public ExceededUsageLimitFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededUsageLimitFault exceededUsageLimitFault, Throwable cause) {
        super(message, cause);
        this.exceededUsageLimitFault = exceededUsageLimitFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.ExceededUsageLimitFault getFaultInfo() {
        return this.exceededUsageLimitFault;
    }
}
