
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.899+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "exceededConcurrentRequestLimitFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class ExceededConcurrentRequestLimitFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.ExceededConcurrentRequestLimitFault exceededConcurrentRequestLimitFault;

    public ExceededConcurrentRequestLimitFault() {
        super();
    }
    
    public ExceededConcurrentRequestLimitFault(String message) {
        super(message);
    }
    
    public ExceededConcurrentRequestLimitFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededConcurrentRequestLimitFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededConcurrentRequestLimitFault exceededConcurrentRequestLimitFault) {
        super(message);
        this.exceededConcurrentRequestLimitFault = exceededConcurrentRequestLimitFault;
    }

    public ExceededConcurrentRequestLimitFault(String message, com.netsuite.webservices.v2016_2.platform.faults.ExceededConcurrentRequestLimitFault exceededConcurrentRequestLimitFault, Throwable cause) {
        super(message, cause);
        this.exceededConcurrentRequestLimitFault = exceededConcurrentRequestLimitFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.ExceededConcurrentRequestLimitFault getFaultInfo() {
        return this.exceededConcurrentRequestLimitFault;
    }
}
