
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.928+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "invalidVersionFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class InvalidVersionFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.InvalidVersionFault invalidVersionFault;

    public InvalidVersionFault() {
        super();
    }
    
    public InvalidVersionFault(String message) {
        super(message);
    }
    
    public InvalidVersionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidVersionFault(String message, com.netsuite.webservices.v2016_2.platform.faults.InvalidVersionFault invalidVersionFault) {
        super(message);
        this.invalidVersionFault = invalidVersionFault;
    }

    public InvalidVersionFault(String message, com.netsuite.webservices.v2016_2.platform.faults.InvalidVersionFault invalidVersionFault, Throwable cause) {
        super(message, cause);
        this.invalidVersionFault = invalidVersionFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.InvalidVersionFault getFaultInfo() {
        return this.invalidVersionFault;
    }
}
