
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.868+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "invalidSessionFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class InvalidSessionFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.InvalidSessionFault invalidSessionFault;

    public InvalidSessionFault() {
        super();
    }
    
    public InvalidSessionFault(String message) {
        super(message);
    }
    
    public InvalidSessionFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidSessionFault(String message, com.netsuite.webservices.v2016_2.platform.faults.InvalidSessionFault invalidSessionFault) {
        super(message);
        this.invalidSessionFault = invalidSessionFault;
    }

    public InvalidSessionFault(String message, com.netsuite.webservices.v2016_2.platform.faults.InvalidSessionFault invalidSessionFault, Throwable cause) {
        super(message, cause);
        this.invalidSessionFault = invalidSessionFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.InvalidSessionFault getFaultInfo() {
        return this.invalidSessionFault;
    }
}
