
package com.netsuite.webservices.v2016_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:15.922+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "invalidAccountFault", targetNamespace = "urn:faults_2016_2.platform.webservices.netsuite.com")
public class InvalidAccountFault extends Exception {
    
    private com.netsuite.webservices.v2016_2.platform.faults.InvalidAccountFault invalidAccountFault;

    public InvalidAccountFault() {
        super();
    }
    
    public InvalidAccountFault(String message) {
        super(message);
    }
    
    public InvalidAccountFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidAccountFault(String message, com.netsuite.webservices.v2016_2.platform.faults.InvalidAccountFault invalidAccountFault) {
        super(message);
        this.invalidAccountFault = invalidAccountFault;
    }

    public InvalidAccountFault(String message, com.netsuite.webservices.v2016_2.platform.faults.InvalidAccountFault invalidAccountFault, Throwable cause) {
        super(message, cause);
        this.invalidAccountFault = invalidAccountFault;
    }

    public com.netsuite.webservices.v2016_2.platform.faults.InvalidAccountFault getFaultInfo() {
        return this.invalidAccountFault;
    }
}
