
package com.netsuite.webservices.v2014_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:05.465+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "exceededRecordCountFault", targetNamespace = "urn:faults_2014_2.platform.webservices.netsuite.com")
public class ExceededRecordCountFault extends Exception {
    
    private com.netsuite.webservices.v2014_2.platform.faults.ExceededRecordCountFault exceededRecordCountFault;

    public ExceededRecordCountFault() {
        super();
    }
    
    public ExceededRecordCountFault(String message) {
        super(message);
    }
    
    public ExceededRecordCountFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRecordCountFault(String message, com.netsuite.webservices.v2014_2.platform.faults.ExceededRecordCountFault exceededRecordCountFault) {
        super(message);
        this.exceededRecordCountFault = exceededRecordCountFault;
    }

    public ExceededRecordCountFault(String message, com.netsuite.webservices.v2014_2.platform.faults.ExceededRecordCountFault exceededRecordCountFault, Throwable cause) {
        super(message, cause);
        this.exceededRecordCountFault = exceededRecordCountFault;
    }

    public com.netsuite.webservices.v2014_2.platform.faults.ExceededRecordCountFault getFaultInfo() {
        return this.exceededRecordCountFault;
    }
}
