
package com.netsuite.webservices.v2014_2.platform;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.1.4
 * 2017-02-06T17:32:05.440+02:00
 * Generated source version: 3.1.4
 */

@WebFault(name = "invalidCredentialsFault", targetNamespace = "urn:faults_2014_2.platform.webservices.netsuite.com")
public class InvalidCredentialsFault extends Exception {
    
    private com.netsuite.webservices.v2014_2.platform.faults.InvalidCredentialsFault invalidCredentialsFault;

    public InvalidCredentialsFault() {
        super();
    }
    
    public InvalidCredentialsFault(String message) {
        super(message);
    }
    
    public InvalidCredentialsFault(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidCredentialsFault(String message, com.netsuite.webservices.v2014_2.platform.faults.InvalidCredentialsFault invalidCredentialsFault) {
        super(message);
        this.invalidCredentialsFault = invalidCredentialsFault;
    }

    public InvalidCredentialsFault(String message, com.netsuite.webservices.v2014_2.platform.faults.InvalidCredentialsFault invalidCredentialsFault, Throwable cause) {
        super(message, cause);
        this.invalidCredentialsFault = invalidCredentialsFault;
    }

    public com.netsuite.webservices.v2014_2.platform.faults.InvalidCredentialsFault getFaultInfo() {
        return this.invalidCredentialsFault;
    }
}
